apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0
        value:
          name: demo-container
          image: gcr.io/silver-agility-460013-n1/my-app:latest
          ports:
            - containerPort: 8000
      - op: add
        path: /spec/replicas
        value: 3
  - target:
      kind: Service
      name: my-demo-service
    patch: |-
      - op: add
        path: /spec/ports/0/targetPort
        value: 8000                 # same as containerPort
